:PROPERTIES:
:ID:       03464369-4a57-478c-ba60-ddf5290f0717
:END:
#+EXPORT_OPTIONS: toc:t
#+title: All Posts
#+hugo_base_dir: ../
* DONE How to use =sops-nix= to manage secrets on NixOS :nixos:security:ATTACH:howto:security:
CLOSED: [2023-11-19 Sun 20:05]
:PROPERTIES:
:Added:    [2023-10-03 Tue 17:32]
:ID:       dac881f2-0e60-4644-8628-b208557b5418
:LINK:     https://github.com/Mic92/sops-nix
:EXPORT_OPTIONS: toc:t
:EXPORT_FILE_NAME: ./sops-nix
:ORG_ATTACH_FILES: sops-nix.pdf
:END:
:LOGBOOK:
- State "DONE"       from              [2023-11-19 Sun 20:05]
- Refiled on [2023-11-19 Sun 20:02]
:END:

** Motivation & Concepts
:PROPERTIES:
:ID:       870a2927-2a44-4161-b2fb-534740aed350
:END:
The concept of "secrets" in a software project is pretty straightforward- it can be anything from SSH keys, API keys, passwords, anything that your project takes as a parameter and you don't want published.

NixOS configurations are confusing, and are some of the deepest and most important software projects you will use on your NixOS machine. They're also likely to be rife with secrets- in my own configuration, I set even the password for my user account using ~configuration.nix~.

As such, it's useful to have a way to host your configuration publicly without needing to keep a separate copy secret-free. [[https://github.com/Mic92/sops-nix][sops-nix]] is one such solution.

*** Concepts
:PROPERTIES:
:ID:       a0f91df6-7c44-4430-a51f-d92ef78d53a0
:END:
The manual is very comprehensive, but the basic idea is the following:
#+begin_quote
1. Create a config yaml file to select which users/machines have access to certain private keys
2. Create a secrets yaml detailing your secrets in plain-text
3. [[https://github.com/getsops/sops][sops]] encrypts this file using the keys specified in the config
4. Then, declare the secrets in ~configuration.nix~. sops-nix will decrypt the secrets at evaluation time, and store them in a directory in ~/run/secrets~
5. Refer to secrets in subsequent generations using [[https://nixos.org/manual/nix/stable/language/string-interpolation][string interpolation]][fn:1]
#+end_quote
** Setup
:PROPERTIES:
:ID:       76d93607-4e53-4b92-8bed-80274b8aff98
:END:

1. Make a .sops.yaml file with your hosts(') public key of choice (you can use age, or the tool ~ssh-age~)
2. Make a =secrets/= dir and add any =secret.yaml= to it
   - To make a secret.yaml, set your =$EDITOR= and then run =sops /path/to/secret.yaml=.
3. Add any client (/to be deployed to/) machine's  public key to =keys:=
   - If using =ssh-to-age=, make sure to use the =/etc/ssh/ssh_host_ed25519_key.pub= file as the input public key. Neither the ~authorized_keys.d~ file nor any other public key will be detected automatically by sops without more configuration (as of [2023-10-03 Tue 17:38])
4. Add the client's name to =key_groups: -age:=
5. If you are adding new keys, make sure to run =sops updatekeys /path/to/secret.yaml= to re-encrypt the existing secrets
6. Set the following options in configuration.nix:
   #+begin_src nix
{
    sops.defaultSopsFile = /path/to/secret.yaml;
    sops.age.keyFile = /path/to/age/keys.txt;
}
   #+end_src

   + Frequently, ~/path/to/age/keys.txt~ will be =/home/<username>/.config/sops/age/keys.txt;=
   
7. *For each secret "key_name" in secret.yaml* add =sops.secrets.key_name = { };= to configuration.nix
At build time, secrets are placed in plaintext files under =/run/secrets=. Refer to secret values in ~configuration.nix~ by using ="${builtins.readFile /run/secrets/secretname}"=.
** Special cases & further reading
:PROPERTIES:
:ID:       e8c9573e-ed44-4fef-b4d3-941c5a5947e7
:END:
This post isn't meant to be comprehensive. The (frankly exhaustive) sops-nix documentation should be the first and final source on its configuration.

However, there are a few special cases worth mentioning.
*** Deploying twice?
:PROPERTIES:
:ID:       110fc207-aad0-4190-8129-a61d6a5cad0a
:END:
Something you may notice is that if you attempt to switch to a configuration that both declares new secrets and references said secrets at the same time, evaluation will fail.

This is because the method used in this post to refer to secrets (~builtins.readFile /run/secrets/...~) depends on the secrets already existing under that directory- which isn't the case until nix has fully evaluated a valid configuration that declares them.

What this means practically is that you need to first switch to a configuration which declares the secrets ([[id:a0f91df6-7c44-4430-a51f-d92ef78d53a0][step four]]) and only /then/ switch to a configuration that references them. There are a few more nuances and tricks relating to this.
**** Use a deployment tool
:PROPERTIES:
:ID:       d68dd66e-f918-4073-8867-c2ffb8217ec2
:END:
There are a /lot/ of [[https://nix-community.github.io/awesome-nix/#deployment-tools][deployment tools]] for NixOS. A deployment tool basically controls the building of configurations and transferring of those configurations (sometimes as a thin wrapper around [[https://www.haskellforall.com/2023/01/announcing-nixos-rebuild-new-deployment.html][nixos-rebuild]]) to various machines, which may or not be remote.

I personally [[id:b349af53-bb24-4813-87a9-2e87fd82f417][use deploy-rs]].

A deployment tool can make it trivial to deploy new secrets to remote machines.

Because secret substitution (interpolation) happens at evaluation time, if you build a configuration remotely on a machine which already has the new secrets installed, you can skip the separate declaration step.
#+begin_quote
[...] /if you build a configuration remotely on a machine which already has the new secrets installed, you can skip the separate declaration step./
#+end_quote
**** Housekeeping
:PROPERTIES:
:ID:       da76cc2e-6451-406a-a99d-19bbaaabebbb
:END:
If you opt to dedicate one of your machines as a builder for multiple configurations, it might be a good idea to store your secrets in one [[https://nixos.wiki/wiki/NixOS_modules][module]].

This way, you can be sure you've actually included all of your secrets, and don't have to hunt through your configuration.

Though, of course, NixOS will give you an error if one is missing, and the message is uncharacteristically helpful:
#+begin_src bash
error: opening file '/run/secrets/missing_secret': No such file or directory
#+end_src
*** Managing user secrets: ~neededForUsers~
:PROPERTIES:
:ID:       d0eba60b-a295-463d-aa18-dcaf48ba013f
:END:
The sops-nix documentation [[https://github.com/Mic92/sops-nix#setting-a-users-password][mentions]] extra settings for secrets needed before users are created, like, especially, a user's password.

#+begin_quote
/The settings for a secret are specified in the (usually empty) attribute set when you declare it:/
#+begin_src nix
sops.secrets.key_name = {
  #... settings go here ...
};
#+end_src
#+end_quote
In particular, when a secret is required before users are bootstrapped, you must set its ~neededForUsers~ to ~true~.
* DONE "how do i use nixos?" 🥺
CLOSED: [2023-11-19 Sun 21:28]
:PROPERTIES:
:ID:       9e1967c9-4857-4e1f-8ef2-882a5c67500f
:EXPORT_HUGO_TYPE: homepage
:EXPORT_FILE_NAME: ./_index
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2023-11-19 Sun 21:28]
:END:
NixOS is hard. Maybe it is bad to use. I am unemployed, so I figured out how to do some stuff. This is where I post about that.
* DONE How to actually exchange SSH keys (passwordless SSH) :linux:howto:security:
CLOSED: [2023-11-19 Sun 20:05]
:PROPERTIES:
:Added: [2023-11-19 Sun 09:17]
:EXPORT_FILE_NAME: ./ssh-keys
:ID:       0a937d68-0ea5-4bf4-90a9-d699e88947a6
:END:
:LOGBOOK:
- State "DONE"       from              [2023-11-19 Sun 20:05]
- Refiled on [2023-11-19 Sun 20:02]
:END:
SSH should be 1-to-1 for device-to-key
1. Run ~ssh-keygen -t ed25519 -N ''~ to generate /one unique key/ per machine, do not overwrite!
   + You should probably use the type of key in this command, see [[https://wiki.archlinux.org/title/SSH_keys#Ed25519][the archwiki]] and surrounding discussion for more details
2. ~ssh-copy-id user@host~ for the user and host you want to log into
3. Do the same thing from the other machine

You should now be able to login to either machine from the other without requiring a password.
* DONE Using ~deploy-rs~ with a conventional Nix flake configuration system :nixos:howto:
CLOSED: [2023-11-19 Sun 20:05]
:PROPERTIES:
:Added: [2023-11-19 Sun 12:20]
:EXPORT_FILE_NAME: ./deploy-rs
:ID:       b349af53-bb24-4813-87a9-2e87fd82f417
:END:
:LOGBOOK:
- State "DONE"       from              [2023-11-19 Sun 20:05]
- Refiled on [2023-11-19 Sun 20:02]
:END:
1. [[id:0a937d68-0ea5-4bf4-90a9-d699e88947a6][Exchange SSH keys]] between the appropriate users (root on the client machine, if you intend to use ~nixpkgs.lib.nixosSystem~-created configurations).
2. Add a ~deploy~ output like:
   #+begin_src nix
{
  ...
        deploy.nodes = {
        host_name = {
            hostname = "${builtins.readFile /run/secrets/host_name_ip}";
            profiles.system = {
            user = "root";
            path = deploy-rs.lib.x86_64-linux.activate.nixos
                self.nixosConfigurations.host_name;
            };
        };
        # ... more nodes ...
        };
  ...
}
   #+end_src
   - The ~builtins...~ interpolation isn't needed if you don't manage your secrets appropriately with ~sops-nix~.
3. Add [[https://github.com/serokell/deploy-rs][deploy-rs]] as a flake input the usual way
4. Add the deploy-rs binary *from the flake input* to the list of installed packages, like you would with other flake-installed binaries (thorium, etc.)
   - If you just use the deploy-rs that comes with ~nixpkgs~ or a random ~nix-shell~, you will have a ton of weird issues
5. Use ~sudo deploy . -- --impure~ to deploy to your machines
   - ~sudo~ is only necessary if you need to deploy secrets kept in /run, like with ~sops-nix~ (since /run needs root access to read from)
   - ~-- --impure~ is only necessary if you have flake impurities (like sops secrets)
     + The extra ~--~ is to tell deploy-rs that you are trying to pass the argument ~--impure~ to the underlying ~nixos-rebuild~ call. See ~deploy --help~.

* DONE An addendum to a "new" deployment tool
CLOSED: [2023-11-20 Mon 17:39]
:PROPERTIES:
:ID:       5bab398b-4018-48c5-ba08-44809b5367a2
:EXPORT_FILE_NAME: ./nixos-rebuild
:END:
:LOGBOOK:
- State "DONE"       from              [2023-11-20 Mon 17:39]
:END:
There's this [[https://www.haskellforall.com/2023/01/announcing-nixos-rebuild-new-deployment.html][awesome blog-post]] about using ~nixos-rebuild~ as a tool to deploy to remote NixOS machines. If you're new to the world of deploying NixOS machines, you might not know that there are [[https://nix-community.github.io/awesome-nix/#deployment-tools][many]].

Some have varying support for flakes, parallel deployments, etc. ~nixos-rebuild~ is not necessarily a solution to all of these problems, but it is a natural (at least on NixOS), [[https://search.nixos.org/packages?channel=23.05&show=nixos-rebuild&from=0&size=50&sort=relevance&type=packages&query=nixos-rebuild][multi-platform]] solution.

However, there is a minor issue. It is recommended to use ~nixos-rebuild~ with ~sudo~ in many cases. If you're using ssh to connect to your remote machine, you need to then pass ~--use-remote-sudo~, like the blog recommends.

It seems, unfortunately, that this flag is [[https://github.com/NixOS/nixpkgs/issues/118655][broken]]:
#+begin_src bash
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
#+end_src

The solution, then, is to [[id:0a937d68-0ea5-4bf4-90a9-d699e88947a6][exchange SSH keys]] with the root user of your client machines.

Just a minor edit to a good post!
* Footnotes
:PROPERTIES:
:ID:       755de290-f056-45e6-81c1-03b2fca41116
:END:

[fn:1] Also see this useful [[https://nixos.org/guides/nix-pills/04-basics-of-language.html#strings][nix-pill]] 
* DONE Installing Gnome 45 :blog:nixos:tricks:gnome:linux:
CLOSED: [2023-11-22 Wed 11:57]
:PROPERTIES:
:Added: [2023-11-21 Tue 15:55]
:ID:       28ed3567-ff0d-47f5-b8d9-3b36d96c391b
:EXPORT_FILE_NAME: ./gnome45
:END:
:LOGBOOK:
- State "DONE"       from "IDEA"       [2023-11-22 Wed 11:57]
- Refiled on [2023-11-22 Wed 11:57]
- State "IDEA"       from              [2023-11-21 Tue 15:55]
:END:
I recently spent some time trying to install gnome 45 on my NixOS laptop (which is finally [[https://github.com/NixOS/nixpkgs/pull/247766][merged]] 🥳 thank you NixOS contributors!)

Unfortunately doing so was kind of a pain with my setup. My laptop is an under-powered machine with only 8GB of RAM, and although my desktop has quite a bit more RAM (and a better processor), its NixOS partition is currently a measly 100GB.

So, building it from source was kind of out of the question on my desktop, and it would take forever on my laptop.

After a while, a Hydra job was started for it, so now I could just download from [[https://cache.nixos.org][cache.nixos.org]]. But on the branch it was built for, some of my packages were totally broken.

I learned that you can not only specify different versions of Nixpkgs in the same configuration, but you can also derive your system configuration (like, in particular, the gnome 45 module and settings) from one version, and /your packages from another!/

When doing this, it may be necessary to pass in extra configuration arguments to the version of Nixpkgs you use for packages. In my case, I use a few unfree packages (like Spotify). Here's how I did that:
#+begin_src nix
let pkgs = (import inp.nixpkgsForPackages {config.allowUnfree = true;}); in ... 
#+end_src

There were a few other interesting leads/tricks I discovered throughout the ordeal, which I've included below.
** Tricks
:PROPERTIES:
:ID:       c3bd30f1-cb3b-4804-945d-56a636a67f91
:END:
:LOGBOOK:
- State "IDEA"       from              [2023-11-21 Tue 15:55]
:END:
- Foregoing switching to a configuration until boot (instead of activating while the machine is running) saves memory, time, and is less stressful when trying to conserve disk space
- You can just fully ~(import inp.nixpkgsForPackages {args_go_here})~ in configuration.nix, and pass any ~config.STUFF~ arguments in at ~args_go_here~. This is useful for example when trying to allow unfree configs:
  #+begin_src nix
  let pkgsOld = (import inp.nixpkgsOld { config.allowUnfree = true; }); in ...
  #+end_src
- Experiment with ~--store~ and ~--eval-store~ to speed up builds!
  - URL syntax for these flags is: ~--store 'ssh://HOST'~, etc.
- Hydra stuff
  - When Hydra evaluates branches of Nixpkgs, any evaluations that succeed are immediately deposited in [[https://cache.nixos.org][cache.nixos.org]]
